name: Generate Snake

on:
  schedule:
    - cron: "0 15 * * *" # 毎日自動実行
  workflow_dispatch: # 手動実行
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # GitHub Snakeの生成（ダークモード対応 ＆ ヘビをピンク色に設定）
      - uses: Platane/snk@v3
        with:
          github_user_name: kubodayo
          github_token: ${{ secrets.PAT }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#4B2C1A&color_dots=#ebedf0,#FFEBB5,#F6C8A4,#63B1D5,#4B2C1A
            dist/github-contribution-grid-snake-dark.svg?color_snake=#4B2C1A&color_dots=#161b22,#FFEBB5,#F6C8A4,#63B1D5,#4B2C1A

      # 生成された画像を 'output' ブランチに保存
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
